---
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.1.0
    hooks:
      - id: trailing-whitespace
      - id: check-added-large-files
      - id: check-docstring-first
      - id: check-merge-conflict
      - id: end-of-file-fixer
  - repo: https://github.com/ambv/black
    rev: stable
    hooks:
      - id: black
        language_version: python3.7
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.782
    hooks:
      - name: Run mypy static analysis tool
        id: mypy
        args: [--no-warn-unused-ignores, --ignore-missing-imports]
        files: src
  - repo: https://github.com/Lucas-C/pre-commit-hooks-safety
    rev: v1.1.3
    hooks:
      - id: python-safety-dependencies-check
  - repo: https://github.com/life4/flakehell/
    rev: master
    hooks:
      - name: Run flakehell static analysis tool
        id: flakehell
        exclude: index.md
